config/routes.rb
RingBase::Application.routes.draw do

  resources :users
  get '/dashboard', :to => redirect('/#/dashboard'), as: :dashboard

  resources :organizations do
    member do
      get 'invite' => 'organizations#invite'
      post 'invitations' => 'organizations#invitations'
    end
  end

  get '/invitations/:token' => 'organizations#complete_invitation', as: 'complete_invitation'
  post 'invitations/:token' => 'organizations#complete_invitation', as: 'post_complete_invitation'

  resources :sessions, only: [:new, :create, :destroy]
  get 'login'    => 'sessions#new',     as: 'login'
  post 'login'   => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: 'logout'

  root 'static#main'

  # Route page not found to 404 page
  # get '*a' => 'static#not_found'

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  validates :title, presence: true

  # TODO: validate pilot_number format

  belongs_to :organization
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :organization
  belongs_to :sender, class_name: 'User'

  valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :recipient_email,
    presence: true,
    format: { with: valid_email_regex }

  validates :organization, presence: true
  validates :sender, presence: true

  before_create :generate_token
  after_create :send_invitation_email

  def invalid?
    used
  end

  def mark_used!
    update_attributes!(used: true)
  end

  private

  def send_invitation_email
    InvitationsMailer.invite(self).deliver
  end

  def generate_token
    begin
      self.token = SecureRandom.urlsafe_base64
    end while self.class.exists?(token: token)
  end
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :users

  has_many :campaigns

  def as_json(options={})
    super(include: [:campaigns])
  end
end

app/models/user.rb
require 'digest/md5'

class User < ActiveRecord::Base
  has_secure_password

  DEFAULT_AVATAR_SIZE = 60 # px

  validates :full_name, presence: true, length: { maximum: 50 }

  valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
    presence: true,
    format: { with: valid_email_regex },
    uniqueness: { case_sensitive: false }

  validates :password, presence: { on: :create },
                       length: { minimum: 5 }, :if => :password_digest_changed?

  belongs_to :organization

  before_create :generate_auth_token

  def peers
    User.where(organization_id: self.organization_id)
        .reject{ |user| user == self }
  end

  def as_json(options)
    {
      id: id,
      full_name: full_name,
      email: email,
      phone_number: phone_number,
      avatar_url: avatar_url
    }
  end

  def avatar_url(options={})
    md5  = Digest::MD5.hexdigest(email.downcase)
    url  = "http://www.gravatar.com/avatar/#{md5}"
    size = options.delete(:size) || DEFAULT_AVATAR_SIZE
    url += "?s=#{size}"
    url
  end

  private

  def generate_auth_token
    self.auth_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  ACCESS_DENIED_PATH = '/'

  helper_method :current_user, :signed_in?, :login_user, :current_organization

  def must_be_logged_in
    respond_to do |format|
      format.html {
        authorized = signed_in?
        reject_unauthorized(authorized, path: login_path)
      }
      format.json {}
      format.js {}
    end
  end

  private

  def current_user
    @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
  rescue ActiveRecord::RecordNotFound
    cookies.delete(:auth_token)
    redirect_to login_path
  end

  def current_organization
    if signed_in?
      @current_organization = Organization.find_by_id(current_user.organization_id)
    end
  end

  def signed_in?
    current_user.present?
  end

  def login_user(user)
    cookies[:auth_token] = user.auth_token
  end

  def reject_unauthorized(authorized=false, options={})
    path = options.delete(:path) || ACCESS_DENIED_PATH

    unless authorized
      respond_to do |format|
        format.html { return redirect_to path }
        format.json { return render json: {} }
      end
    end
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  before_filter :must_be_logged_in, except: [:complete_invitation]

  skip_before_filter :verify_authenticity_token, only: [:invitations]

  # View
  def invite
  end

  def invitations
    @organization = Organization.find(params[:id])

    invitation_email_params.each do |email|
      Invitation.create!(organization: @organization,
                         sender: current_user, recipient_email: email)
    end

    redirect_to dashboard_path
  end


  def complete_invitation
    @invitation = Invitation.find_by(token: params[:token])

    if request.get?
      @user = User.new
      render
    else
      @user = User.new(user_params) do |u|
        u.email = @invitation.recipient_email
      end
      @invitation.organization.users << @user

      if @user.save
        login_user(@user)
        redirect_to dashboard_path
      else
        render :complete_invitation
      end
    end
  end

  private

  def invitation_email_params
    params.require(:invitations).map { |_, attrs| attrs['recipient_email'] }
  end

  def user_params
    params.permit(:full_name, :password, :password_confirmation)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to dashboard_path if signed_in?
  end

  def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      login_user(user)
      redirect_to dashboard_path
    else
      flash[:error] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    cookies.delete(:auth_token)
    return redirect_to root_url
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def main
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json

  def new
    @user = User.new
  end

  def create
    org  = Organization.create!(name: organization_name)
    org.campaigns.create!(title: organization_name, pilot_number: pilot_number)
    @user = org.users.build(user_params)

    if @user.save
      login_user(@user)

      # TODO: hack
      redirect_to "/#/organizations/#{org.id}/invite"
    else
      flash[:error] = "Something went wrong!"
      render :new
    end
  end

  def index
    respond_with current_user.peers.to_json
  end

  private

  def user_params
    params.require(:user).permit(:full_name, :email, :password, :password_confirmation)
  end

  def organization_name
    params.require(:organization_name)
  end

  def pilot_number
    params.require(:pilot_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_error
    if msg = flash[:error]
      content_tag(:div, msg, class: "alert alert-danger")
    end
  end

  def flash_success
    if msg = flash[:success]
      content_tag(:div, msg, class: "alert alert-success")
    end
  end
end

app/helpers/avatar_helper.rb
module AvatarHelper
  def avatar_for(user, options={})
    content_tag :img, '', src: user.avatar_url, class: 'avatar'
  end
end

app/helpers/nav_helper.rb
module NavHelper
  def current_class(path)
    current_page?(path) ? 'active' : ''
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="ringbase">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= yield(:title) + ' | '  if content_for?(:title) %>RingBase</title>
  <%= stylesheet_link_tag :application %>
  <%= csrf_meta_tags %>
</head>

<%# TODO: hack for demo %>
<% body_bg_color = current_page?(login_path) ? '#f6f6f6' : '#fff' %>
<body style="xbackground-color: <%= body_bg_color %>">
  <div class="page-wrap">

    <%= render 'shared/header' %>

    <div class="alert alert-danger connection-error-container" ng-show="$root.brokerError">
      An error occurred while connecting to Ringbase!
    </div>

    <%= yield(:before_container) %>

    <% container_class = (!signed_in? && current_page?(root_path)) ? '' : 'xcontainer' %>
    <div class="<%= container_class %> app-content-container">
      <% if signed_in? %>

          <%= render 'shared/sidebar' %>

          <div class="main-content">
            <div class="main-content-inner">
              <div ng-view></div>
            </div>
          </div>

      <% else %>
        <%= yield %>
      <% end %>
    </div><!-- .container -->

  </div>


  <% if signed_in? %>
    <script type="text/javascript">
      window.current_user = JSON.parse('<%= raw current_user.to_json %>');
      window.current_organization = JSON.parse('<%= raw current_organization.to_json %>');
    </script>
  <% end %>

  <%= javascript_include_tag :application %>
</body>
</html>

app/views/organizations/complete_invitation.html.erb
<div class="row">
  <h1 style="margin-bottom:20px; text-align:center;">Welcome to RingBase</h1>

  <div class="col-md-4 col-md-offset-4">
    <%= form_tag complete_invitation_path(token: @invitation.token) do %>
      <% if @user.errors.present? %>
        <div class="alert alert-danger">
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= label_tag :email %>
        <%= text_field_tag :email, @invitation.recipient_email, class: 'form-control',
          disabled: 'disabled' %>
      </div>

      <div class="form-group">
        <%= label_tag :full_name %>
        <%= text_field_tag :full_name, '', class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= label_tag :password %>
        <%= password_field_tag :password, '', class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= label_tag :password_confirmation, 'Confirm Password' %>
        <%= password_field_tag :password_confirmation, '', class: 'form-control' %>
      </div>

      <%= submit_tag 'Sign Up', class: 'btn btn-primary pull-right' %>
    <% end %>

  </div>
</div>

app/views/shared/_header.html.erb
<header class="navbar navbar-inverse">
  <div class="container">

    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if signed_in? %>
        <%= link_to current_organization.name, dashboard_path, class: 'navbar-brand' %>
      <% end %>
    </div>

    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li><%= link_to "Log Out", logout_path %></li>
        <% else %>
          <li><%= link_to 'Create Account', new_user_path %></li>
          <li><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
    </nav>

  </div>
</header>

app/views/shared/_sidebar.html.erb
  <div class="sidebar-container">

    <div class="panel panel-default">
      <div class="panel-heading">
        <%= avatar_for(current_user) %>

        <div class="sidebar-agent-info-container">
          <p><%= current_user.full_name %></p>

          <div class="status-switch-container">
            <div class="status-switch">
              <input type="checkbox" class="status-switch-checkbox" id="agent-status-switch" checked>
              <label class="status-switch-label" for="agent-status-switch">
                <div class="status-switch-inner"></div>
                <div class="status-switch-switch"></div>
              </label>
            </div>
          </div>
        </div>

      </div>
      <ul class="nav nav-sidebar">
        <li><a href="/" target="_self"><i class="glyphicon glyphicon-home"></i>Dashboard</a></li>
        <li><a href="/#/settings"><i class="glyphicon glyphicon-cog"></i>Settings</a></li>
      </ul>
    </div><!-- .panel-default -->

  </div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <h2 style="margin-bottom:25px;text-align:center;">Create Your Account</h2>

    <%= form_for @user, html: { class: "whitebox" } do |f| %>

      <% if @user.errors.present? %>
        <div class="alert alert-danger">
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :full_name %>
        <%= f.text_field :full_name, autofocus: true, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :organization_name %>
        <%= text_field_tag :organization_name, '', class: "form-control" %>
      </div>

      <div class="form-group">
        <%= label_tag :pilot_number, 'Organization Phone Number' %>
        <%= text_field_tag :pilot_number, '', class: "form-control" %>
      </div>

      <%= f.submit "Submit", class: "btn btn-primary pull-right"%>
    <% end %>

	</div>
</div>